version: "3.8"

services:
  app:
    container_name: my-node-app
    build: .
    ports:
      - "80:80" 
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
